version: 2
updates:
  - package-ecosystem: "composer" 
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Coho04"
    reviewers:
      - "Coho04"
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "daily"
    assignees:
      - "Coho04"
    reviewers:
      - "Coho04"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Coho04"
    reviewers:
      - "Coho04"         
